helm:
  parameters:
  - name: image.repository
    value: 427673671759.dkr.ecr.us-east-1.amazonaws.com/petclinic
    forcestring: false
  - name: image.tag
    value: 6-9621e40
    forcestring: true
  - name: replicaCount
    value: "1"
    forcestring: false
  - name: image.name
    value: 427673671759.dkr.ecr.us-east-1.amazonaws.com/petclinic
    forcestring: true
